[[mingw-w64]]
arch = "x86_64"
git-tree-sha1 = "fdff308295487f361ef6e8dc2d27f5abe8a6eee9"
os = "windows"
lazy = true

    [[mingw-w64.download]]
    sha256 = "fe3f401bc936fbe6af940b26c5e0f266f762a3416f979c706e599b24082dc5c7"
    url = "https://github.com/JuliaLang/PackageCompiler.jl/releases/download/v1.0.0/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.tar.gz"

[[mingw-w64]]
arch = "i686"
git-tree-sha1 = "bc760d8ef1b4840e55a36bd361587b4975af811f"
os = "windows"
lazy = true

    [[mingw-w64.download]]
    sha256 = "ab0abb76384ce9b657141d3a54150d0b865f9c06576caa7901a6c8429c9008e5"
    url = "https://github.com/JuliaLang/PackageCompiler.jl/releases/download/v1.0.0/i686-8.1.0-release-posix-sjlj-rt_v6-rev0.tar.gz"
