name: Nightly CI

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'release-*'
    tags: '*'
  merge_group: # GitHub Merge Queue

concurrency:
  # Skip intermediate builds: all builds except for builds on the `master` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test-nightly:
    # We do not run the full test suite on tags, because we already ran it on master before we made the release.
    # We do build the docs on tags.
    if: (github.event_name != 'push') || (github.ref_type != 'tag')
    timeout-minutes: 150
    runs-on: ${{ matrix.github-runner }}
    strategy:
      max-parallel: 5 # leave space for other runs in the JuliaLang org, given these tests are long
      fail-fast: false
      matrix:
        include:
          # 1. We intentionally put nightly CI into a separate YAML
          #    file (`ci.nightly.yml` versus the main `ci.yml` file).
          #    This allows us to enable and disable the nightly CI
          #    workflow from the GitHub web UI, without having any
          #    impact on the main CI.
          # 2. We intentionally only run one CI job on Julia nightly,
          #    in order to conserve CI resources.
          # 3. This CI only runs on Julia nightly. It doesn't run on
          #    Julia pre-releases. For CI on Julia pre-releases, see
          #    the main CI workflow file.
          - julia-version: 'nightly'
            julia-wordsize: '64'
            github-runner: ubuntu-latest
            coverage: true
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: julia-actions/setup-julia@9b79636afcfb07ab02c256cede01fe2db6ba808c # v2.6.0
        with:
          version: ${{ matrix.julia-version }}
          # If `julia-wordsize` is 32, then we set `arch` to `x86`, because we know that
          # 32-bit builds of Julia are only available for x86.
          #
          # If `julia-wordsize` is 64, then we set `arch` to `${{ runner.arch }}`, which
          # GitHub will automatically expand to the correct value (`x86_64` or `aarch64`)
          # based on the architecture of the underlying GitHub Runner (virtual machine).
          arch: ${{ github.ref == '32' && 'x86' || runner.arch }}
      - uses: julia-actions/cache@824243901fb567ccb490b0d0e2483ccecde46834 # v2.0.5
      - uses: julia-actions/julia-runtest@1e03e0122a598a569004c1e26950e2547b350ec0 # v1.11.1
        with:
          coverage: ${{ matrix.coverage }}
      - uses: julia-actions/julia-processcoverage@03114f09f119417c3242a9fb6e0b722676aedf38 # v1.2.2
      - uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          file: lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
