name: Run tests
on:
  pull_request:
    branches:
      - 'master'
      - 'release-*'
  push:
    branches:
      - 'master'
      - 'release-*'
    tags: '*'
concurrency:
  group: ${{ github.head_ref || github.ref_name || github.run_id }}
  cancel-in-progress: true
jobs:
  test:
    timeout-minutes: 90
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - '1.6'
          - '1.7'
          - '1.8'
          - '1.9-nightly'
          - 'nightly'
        julia-arch:
          - 'x64'
          - 'x86'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        coverage:
          - 'true'
          - 'false' # needed for 1.9+ to test from a session using pkgimages
        exclude:
          - os: macOS-latest
            julia-arch: x86
          - julia-version: '1.6'
            coverage: 'false'
          - julia-version: '1.7'
            coverage: 'false'
          - julia-version: '1.8'
            coverage: 'false'
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-runtest@latest
        with:
          coverage: ${{ matrix.coverage }}
      - uses: julia-actions/julia-processcoverage@latest
      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info
